### ISSUE TITLE
Friend list bug

### ISSUE THREAD

**Issue by Sheshank-s** [WorldLanguages/isOnlineBETA#14]
For some reason, friend list doesn't  work on any of my windows 10 laptops? I use chrome. If I get the version on the chrome extensions page it works, but this versions friend list doesn't work. Whenever I click add friends, nothing happens.

I just got a new laptop today and it didn't work on that one, so it can't be a problem with a virus or something :P

**Comment by joker314** [comment]
And you're pressing "+ friends" and nothing happens? Hmmm... is your friend list turned on 😛... it's just that I can't reproduce the issue that you're talking about.

**Comment by Sheshank-s** [comment]
Yes. Without friend list turned on + friends wont show up

**Comment by joker314** [comment]
That's intentional, I think? If it's off, it's not meant to work.

**Comment by joker314** [comment]
Did it work differently before?

**Comment by Sheshank-s** [comment]
No..

**Comment by Sheshank-s** [comment]
If I use the version on the chrome store it works

**Comment by joker314** [comment]
Oh right, so it's an inconsistency? Personally, I like the new way (friend list has to be turned on for it to work)

If the friend list feature is disabled, then any of its features should be hidden.

After all, there's no guarantee that it has even acquired the notifications permission when it's off...

**Comment by joker314** [comment]
I think this will be resolved when we seperate the friend list and the notifications?

**Comment by DeleteThisAcount** [comment]
Same happens to me on a windows 10 laptop. Something in the friend list because when I use the friendlist.js from the non beta it works.

The betas friend list is broken

**Comment by joker314** [comment]
Just to clarify, @DeleteThisAcount, when friend list is on, does everything work?

**Comment by Sheshank-s** [comment]
Not for me D: When friend list is on nothing works :P

**Comment by joker314** [comment]
Oh, that's not good.. screenshots? Console messages?

**Comment by Sheshank-s** [comment]
None

**Comment by joker314** [comment]
No console messages? There have to be console messages..

Hmm.

**Comment by Sheshank-s** [comment]
None :P

**Comment by joker314** [comment]
There's always a console message, pretty sure..

**Comment by Sheshank-s** [comment]
I dunno what to say, there are no console messages :P

**Comment by joker314** [comment]
Fair enough... :P

**Comment by joker314** [comment]
So what do we do? Revert each commit until it starts working again?

**Comment by Sheshank-s** [comment]
Hmmm... I think we have no other choice :(

**Comment by DeleteThisAcount** [comment]
um dont revert all of them... i know what commit broke it... just update the friendlist.js with the friendlist.js from the normal isonline code

**Comment by DeleteThisAcount** [comment]
@joker314 no it doesnt work

**Comment by joker314** [comment]
@DeleteThisAcount Hmm, feel free to do it yourself, but we'll try.. 😛

**Comment by joker314** [comment]
Okay, well, we reverted friendlist.js, that solves the issue.
