### ISSUE TITLE
FAQ padding doesn't elicit pointer cursor

### ISSUE THREAD

**Issue by joker314** [WorldLanguages/isOnlineBETA#19]
When you hover over an question in the FAQs section, then you should get a pointer cursor. This happens when you hover in-line with the text. However, if you hover below the text, but still on the element (it's possible because of padding), it uses the default cursor. This is bad because this section is also clickable and so we should make that clear.

**Comment by Sheshank-s** [comment]
Hmm.. Ill fix this :D

**Comment by Sheshank-s** [comment]
Apparently, you already fixed it, cuz it works for me now

**Comment by joker314** [comment]
*shrug* I don't think so...

**Comment by Sheshank-s** [comment]
are  you sure, ill send screenshot

**Comment by Sheshank-s** [comment]
nvm how do i send screenshot with my cursor :P

**Comment by joker314** [comment]
I don't know either.. but here's a screenshot explaining where I experience the bug.

Blue represents where it doesn't work; and red where it does.

![image](https://user-images.githubusercontent.com/18113170/29726959-96193622-89da-11e7-8fd2-689c606f1c11.png)

**Comment by Sheshank-s** [comment]
Oh ok, will do

**Comment by Sheshank-s** [comment]
done
