### ISSUE TITLE
Validation code Length of 4 

### ISSUE THREAD

**Issue by kickofline** [WorldLanguages/isOnlineBETA#21]
so it wont fill in the code

**Comment by ed-cooper** [comment]
Could you be more specific please?

**Comment by kickofline** [comment]
@chooper100 when you validate your account, sometimes you can get a code of length 4, and the code is set up to only fill in the comment on the validation studio when the code has a lenght of 5 or 6

**Comment by WorldLanguages** [comment]
The validation length could be of any length from 1 to 6, I'll change the code so it fills any hexadecimal string of length 1-6

**Comment by WorldLanguages** [comment]
Changed in last commit
