### ISSUE TITLE
iO extras

### ISSUE THREAD

**Issue by DeleteThisAcount** [WorldLanguages/isOnlineBETA#23]
I made an account for isonline extra features. (Like the NavBar design) Could you please change the code so that DiscussButton has the enable button but iOExtras has the other extra features?

Thanks,
DeleteThisAcount

PS: Read my other issue.

**Comment by WorldLanguages** [comment]
![image](https://user-images.githubusercontent.com/17484114/30249666-fe9d95ce-9616-11e7-9b89-eba9a5101d9d.png)
woah...

btw, no, we're using our own accounts, and DiscussButton only.

**Comment by DeleteThisAcount** [comment]
okay :(
