### ISSUE TITLE
Friend List Bug

### ISSUE THREAD

**Issue by joker314** [WorldLanguages/isOnlineBETA#6]
This _could_ just be an issue with my internet connection, but I--

1) Enable the friend list
2) Disable it
3) Lose intenet access
4) Regain internet access
5) Re-enable friend list

This is probably just my internet connection, perhaps I accidentally re-enabled the friend list while there was no internet, but the message I go was something like "Error: re-validate to fix". Disabling then immediately re-enabling the friend list fixes the issue

**Comment by WorldLanguages** [comment]
this is just a webhook test

**Comment by WorldLanguages** [comment]
this is just a webhook test

**Comment by WorldLanguages** [comment]
another one

**Comment by joker314** [comment]
I'm going to close this since it looks like it's resolved.
